namespace :db do
  namespace :log do
    desc "truncate logs generated by DBLogger for current environment"
    task :clear => :environment do
      LoggedEvent.delete_all(["environment = ?", RAILS_ENV])
    end
  end
end